//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRALI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConfGeneral
    {
        public int id { get; set; }
        public string nombreCompletoInstitucion { get; set; }
        public string nombreCortoInstitucion { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string logo { get; set; }
        public string nit { get; set; }
        public string rfc { get; set; }
        public string codigoMined { get; set; }
        public string web { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
    }
}
