//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRALI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOpcionesSistema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOpcionesSistema()
        {
            this.tblOpcionesxPerfil = new HashSet<tblOpcionesxPerfil>();
        }
    
        public int id { get; set; }
        public string nombreModulo { get; set; }
        public string descripcionModulo { get; set; }
        public Nullable<int> idPadre { get; set; }
        public string nombreVista { get; set; }
        public string nombreIconoMenu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOpcionesxPerfil> tblOpcionesxPerfil { get; set; }
    }
}
