//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRALI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPadredeFamilia
    {
        public int idPadredeFamilia { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string telefonoFijo { get; set; }
        public string telefonoMovil { get; set; }
        public string profesion { get; set; }
        public string lugardeTrabajo { get; set; }
        public string dui { get; set; }
        public string email { get; set; }
        public string parentesco { get; set; }
        public string responsabledeAlumno { get; set; }
        public Nullable<int> idAlumno { get; set; }
    
        public virtual tblEstudiante tblEstudiante { get; set; }
    }
}
