//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRALI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResponsableEstudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblResponsableEstudiante()
        {
            this.tblEstudiante = new HashSet<tblEstudiante>();
        }
    
        public int idResponsable { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string telefonoFijo { get; set; }
        public string telefonoMovil { get; set; }
        public string dui { get; set; }
        public string microbus { get; set; }
        public string telefonoFijoMicrobus { get; set; }
        public string telefonoMovilMicrobus { get; set; }
        public string numeroPlaca { get; set; }
        public string marca { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string creadoPor { get; set; }
        public Nullable<System.DateTime> fechaActualizado { get; set; }
        public string actualizadoPor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEstudiante> tblEstudiante { get; set; }
    }
}
