//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRALI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UsuariosSistema
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string nombreCompleto { get; set; }
        public string estado { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string nombrePerfil { get; set; }
    }
}
